Repository kzi-nastava/iks-project-event-planner-siit-2024-team-11, pull requests merged in 2025-07, with the labels that each got.

#54 Tests/user registration and event management
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/agenda-creation/agenda-creation.component.html
  Eventy/src/app/events/agenda-creation/agenda-creation.component.ts
  Eventy/src/app/events/all-event-types/all-event-types.component.html
  Eventy/src/app/events/all-event-types/all-event-types.component.ts
  Eventy/src/app/events/edit-event-type/edit-event-type.component.html
  Eventy/src/app/events/edit-event-type/edit-event-type.component.ts
  Eventy/src/app/events/event-creation-basic-information/event-creation-basic-information.component.html
  Eventy/src/app/events/event-creation-basic-information/event-creation-basic-information.component.ts
  Eventy/src/app/events/event-details/event-details.component.ts
  Eventy/src/app/events/event-organization/event-organization.component.html
  Eventy/src/app/events/event-organization/event-organization.component.ts
  Eventy/src/app/events/invitations-sending/invitations-sending.component.html
  Eventy/src/app/events/model/events.model.ts
  Eventy/src/app/infrastructure/auth/auth.service.mock.ts
  Eventy/src/app/infrastructure/auth/auth.service.spec.ts
  Eventy/src/app/infrastructure/auth/login-form/login-form.component.html
  Eventy/src/app/infrastructure/auth/register-organizer/register-organizer.component.spec.ts
  Eventy/src/app/infrastructure/auth/register-organizer/register-organizer.component.ts
  Eventy/src/app/infrastructure/auth/register-provider/register-provider.component.spec.ts
  Eventy/src/app/infrastructure/auth/register-provider/register-provider.component.ts
  Eventy/src/app/infrastructure/auth/upgrade-organizer/upgrade-organizer.component.ts
  Eventy/src/app/infrastructure/auth/upgrade-provider/upgrade-provider.component.ts
  Eventy/src/app/layout/nav-bar/nav-bar.component.html
  Eventy/src/app/shared/error-dialog/error-dialog.component.html
  Eventy/src/app/user-management/edit-provider-form/edit-provider-form.component.html
  Eventy/src/app/user-management/edit-provider-form/edit-provider-form.component.ts
  Eventy/src/app/user-management/edit-user-form/edit-user-form.component.html
  Eventy/src/app/user-management/edit-user-form/edit-user-form.component.ts
  Eventy/src/app/user-management/my-profile-page/my-profile-page.component.css
  Eventy/src/app/user-management/my-profile-page/my-profile-page.component.html
  Eventy/src/app/user-management/my-profile-page/my-profile-page.component.ts
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.css
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.html
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.ts
Labels: test

#56 Feature/budget
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/budget-menu-category-edit-dialog/budget-menu-category-edit-dialog.component.css
  Eventy/src/app/events/budget-menu-category-edit-dialog/budget-menu-category-edit-dialog.component.html
  Eventy/src/app/events/budget-menu-category-edit-dialog/budget-menu-category-edit-dialog.component.spec.ts
  Eventy/src/app/events/budget-menu-category-edit-dialog/budget-menu-category-edit-dialog.component.ts
  Eventy/src/app/events/budget-menu-category-input-dialog/budget-menu-category-input-dialog.component.css
  Eventy/src/app/events/budget-menu-category-input-dialog/budget-menu-category-input-dialog.component.html
  Eventy/src/app/events/budget-menu-category-input-dialog/budget-menu-category-input-dialog.component.spec.ts
  Eventy/src/app/events/budget-menu-category-input-dialog/budget-menu-category-input-dialog.component.ts
  Eventy/src/app/events/budget-menu-category-item/budget-menu-category-item.component.css
  Eventy/src/app/events/budget-menu-category-item/budget-menu-category-item.component.html
  Eventy/src/app/events/budget-menu-category-item/budget-menu-category-item.component.spec.ts
  Eventy/src/app/events/budget-menu-category-item/budget-menu-category-item.component.ts
  Eventy/src/app/events/budget-menu-category/budget-menu-category.component.css
  Eventy/src/app/events/budget-menu-category/budget-menu-category.component.html
  Eventy/src/app/events/budget-menu-category/budget-menu-category.component.spec.ts
  Eventy/src/app/events/budget-menu-category/budget-menu-category.component.ts
  Eventy/src/app/events/budget-menu-solution-selection-dialog/budget-menu-solution-selection-dialog.component.css
  Eventy/src/app/events/budget-menu-solution-selection-dialog/budget-menu-solution-selection-dialog.component.html
  Eventy/src/app/events/budget-menu-solution-selection-dialog/budget-menu-solution-selection-dialog.component.spec.ts
  Eventy/src/app/events/budget-menu-solution-selection-dialog/budget-menu-solution-selection-dialog.component.ts
  Eventy/src/app/events/budget-menu/budget-menu.component.css
  Eventy/src/app/events/budget-menu/budget-menu.component.html
  Eventy/src/app/events/budget-menu/budget-menu.component.spec.ts
  Eventy/src/app/events/budget-menu/budget-menu.component.ts
  Eventy/src/app/events/event-details/event-details.component.html
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/model/budget.model.ts
  Eventy/src/app/events/services/budget-service.service.spec.ts
  Eventy/src/app/events/services/budget-service.service.ts
  Eventy/src/app/products/product.service.ts
  Eventy/src/app/solutions/model/solutions.model.ts
  Eventy/src/app/solutions/services/solutions/solution-category.service.ts
Labels: enhancement

#57 [FIX] Added the pin to the map on event details page
  Eventy/src/app/events/event-details/event-details.component.ts
Labels: bug

#59 [FIX] Added role checks, so not every user can access every part of the app
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/layout/nav-bar/nav-bar.component.html
  Eventy/src/app/layout/nav-drawer/nav-drawer.component.html
Labels: bug

#58 Feature/reviews
  Eventy/src/app/events/budget-menu-category/budget-menu-category.component.ts
  Eventy/src/app/reviews/model/review.model.ts
  Eventy/src/app/reviews/review-card/review-card.component.css
  Eventy/src/app/reviews/review-card/review-card.component.html
  Eventy/src/app/reviews/review-card/review-card.component.spec.ts
  Eventy/src/app/reviews/review-card/review-card.component.ts
  Eventy/src/app/reviews/reviews.module.ts
  Eventy/src/app/reviews/service/review.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.css
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
  Eventy/src/app/solutions/solutions.module.ts
Labels: enhancement
