Repository kzi-nastava/iks-project-event-planner-siit-2024-team-11, pull requests merged in 2025-01, with the labels that each got.

#32 Home - EVENTS (Backend)
  Eventy/package-lock.json
  Eventy/package.json
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/all-events/all-events.component.css
  Eventy/src/app/events/all-events/all-events.component.html
  Eventy/src/app/events/all-events/all-events.component.ts
  Eventy/src/app/events/event-card/event-card.component.html
  Eventy/src/app/events/event-card/event-card.component.ts
  Eventy/src/app/events/event-filters/event-filters.component.css
  Eventy/src/app/events/event-filters/event-filters.component.ts
  Eventy/src/app/events/featured-events/featured-events.component.ts
  Eventy/src/app/events/model/event-card.model.ts
  Eventy/src/app/events/services/events/events-service.service.ts
  Eventy/src/app/layout/home/home.component.html
  Eventy/src/app/layout/home/home.component.ts
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.html
Labels: enhancement

#33 Home - SOLUTIONS (Backend)
  Eventy/src/app/events/all-events/all-events.component.ts
  Eventy/src/app/events/event-filters/event-filters.component.ts
  Eventy/src/app/events/event-organization/event-organization.component.ts
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/featured-events/featured-events.component.ts
  Eventy/src/app/events/services/events/events-service.service.spec.ts
  Eventy/src/app/events/services/events/events-service.service.ts
  Eventy/src/app/layout/home/home.component.html
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/products/product-card/product-card.component.ts
  Eventy/src/app/services/my-services-view-card/my-services-view-card.component.html
  Eventy/src/app/services/my-services-view-card/my-services-view-card.component.ts
  Eventy/src/app/services/my-services-view/my-services-view.component.html
  Eventy/src/app/services/my-services-view/my-services-view.component.ts
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.html
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.ts
  Eventy/src/app/services/service-card/service-card.component.html
  Eventy/src/app/services/service-card/service-card.component.ts
  Eventy/src/app/services/services.service.ts
  Eventy/src/app/solutions/all-solutions/all-solutions.component.css
  Eventy/src/app/solutions/all-solutions/all-solutions.component.html
  Eventy/src/app/solutions/all-solutions/all-solutions.component.ts
  Eventy/src/app/solutions/featured-solutions/featured-solutions.component.ts
  Eventy/src/app/solutions/model/solution-card.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.spec.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
  Eventy/src/app/solutions/solution-filters/solution-filters.component.css
  Eventy/src/app/solutions/solution-filters/solution-filters.component.html
  Eventy/src/app/solutions/solution-filters/solution-filters.component.ts
  Eventy/src/app/solutions/solutions.module.ts
  Eventy/src/app/user-management/my-profile-page/my-profile-page.component.ts
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.ts
Labels: enhancement

#34 Reservations - CREATE RESERVATION (Backend)
  Eventy/src/app/events/all-events/all-events.component.css
  Eventy/src/app/events/reservation-select-event/reservation-select-event.component.html
  Eventy/src/app/events/reservation-select-event/reservation-select-event.component.ts
  Eventy/src/app/services/model/reservations.model.ts
  Eventy/src/app/services/my-services-view/my-services-view.component.ts
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.html
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.ts
  Eventy/src/app/services/services/reservations/reservations-service.service.spec.ts
  Eventy/src/app/services/services/reservations/reservations-service.service.ts
  Eventy/src/app/services/services/services/services.service.spec.ts
  Eventy/src/app/services/services/services/services.service.ts
  Eventy/src/app/shared/shared.module.ts
  Eventy/src/app/shared/successful-dialog/successful-dialog.component.css
  Eventy/src/app/shared/successful-dialog/successful-dialog.component.html
  Eventy/src/app/shared/successful-dialog/successful-dialog.component.spec.ts
  Eventy/src/app/shared/successful-dialog/successful-dialog.component.ts
  Eventy/src/app/solutions/all-solutions/all-solutions.component.css
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
Labels: enhancement

#36 Refactor/working with pictures
  Eventy/src/app/events/event-card/event-card.component.html
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/services/service-card/service-card.component.html
Labels: refactor

#37 Improvement/solution categories
  Eventy/src/app/shared/solution-category-input-dialog/solution-category-input-dialog.component.ts
  Eventy/src/app/solutions/model/category.model.ts
  Eventy/src/app/solutions/services/solutions/solution-category.service.ts
  Eventy/src/app/solutions/solution-categories-view/solution-categories-view.component.html
  Eventy/src/app/solutions/solution-categories-view/solution-categories-view.component.ts
  Eventy/src/app/solutions/solution-category-requests-view/solution-category-requests-view.component.html
  Eventy/src/app/solutions/solution-category-requests-view/solution-category-requests-view.component.ts
Labels: improvement

#38 Feature/event details
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/event-card/event-card.component.css
  Eventy/src/app/events/event-card/event-card.component.html
  Eventy/src/app/events/event-card/event-card.component.ts
  Eventy/src/app/events/event-details/event-details.component.css
  Eventy/src/app/events/event-details/event-details.component.html
  Eventy/src/app/events/event-details/event-details.component.spec.ts
  Eventy/src/app/events/event-details/event-details.component.ts
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/model/event-card.model.ts
  Eventy/src/app/events/model/events.model.ts
  Eventy/src/app/events/services/events/events-service.service.ts
Labels: enhancement
