Repository kzi-nastava/iks-project-event-planner-siit-2024-team-11, pull requests merged in 2025-02, with the labels that each got.

#39 Feature/solution details
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/products/product-card/product-card.component.css
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/products/product-card/product-card.component.ts
  Eventy/src/app/services/service-card/service-card.component.css
  Eventy/src/app/services/service-card/service-card.component.html
  Eventy/src/app/services/service-card/service-card.component.ts
  Eventy/src/app/solutions/model/solution-card.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.css
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.spec.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
  Eventy/src/app/solutions/solutions.module.ts
Labels: enhancement

#41 Revert "Feature/solution details"
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/products/product-card/product-card.component.css
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/products/product-card/product-card.component.ts
  Eventy/src/app/services/service-card/service-card.component.css
  Eventy/src/app/services/service-card/service-card.component.html
  Eventy/src/app/services/service-card/service-card.component.ts
  Eventy/src/app/solutions/model/solution-card.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.css
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.spec.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
  Eventy/src/app/solutions/solutions.module.ts
Labels: invalid

#42 Revert 41 revert 39 feature/solution details
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/products/product-card/product-card.component.css
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/products/product-card/product-card.component.ts
  Eventy/src/app/services/service-card/service-card.component.css
  Eventy/src/app/services/service-card/service-card.component.html
  Eventy/src/app/services/service-card/service-card.component.ts
  Eventy/src/app/solutions/model/solution-card.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.css
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.spec.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
  Eventy/src/app/solutions/solutions.module.ts
Labels: enhancement

#40 Feature/event stats
  Eventy/package-lock.json
  Eventy/package.json
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/event-stats/event-stats.component.css
  Eventy/src/app/events/event-stats/event-stats.component.html
  Eventy/src/app/events/event-stats/event-stats.component.spec.ts
  Eventy/src/app/events/event-stats/event-stats.component.ts
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/model/events.model.ts
  Eventy/src/app/events/services/events/events-service.service.ts
  Eventy/src/app/layout/nav-drawer/nav-drawer.component.html
Labels: enhancement

#43 Notifications - FRONTEND & BACKEND
  Eventy/package-lock.json
  Eventy/package.json
  Eventy/src/app/app.component.css
  Eventy/src/app/app.component.html
  Eventy/src/app/app.component.ts
  Eventy/src/app/app.module.ts
  Eventy/src/app/events/all-events/all-events.component.ts
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/model/events.model.ts
  Eventy/src/app/events/services/events/events-service.service.ts
  Eventy/src/app/infrastructure/auth/login-form/login-form.component.ts
  Eventy/src/app/interactions/all-notifications/all-notifications.component.css
  Eventy/src/app/interactions/all-notifications/all-notifications.component.html
  Eventy/src/app/interactions/all-notifications/all-notifications.component.spec.ts
  Eventy/src/app/interactions/all-notifications/all-notifications.component.ts
  Eventy/src/app/interactions/interactions.module.ts
  Eventy/src/app/interactions/model/notification.model.ts
  Eventy/src/app/interactions/notification-card/notification-card.component.css
  Eventy/src/app/interactions/notification-card/notification-card.component.html
  Eventy/src/app/interactions/notification-card/notification-card.component.spec.ts
  Eventy/src/app/interactions/notification-card/notification-card.component.ts
  Eventy/src/app/interactions/services/messages/message.service.spec.ts
  Eventy/src/app/interactions/services/messages/message.service.ts
  Eventy/src/app/interactions/services/notifications/notification.service.spec.ts
  Eventy/src/app/interactions/services/notifications/notification.service.ts
  Eventy/src/app/interactions/services/paginator/custom-mat-paginator-intl.service.spec.ts
  Eventy/src/app/interactions/services/paginator/custom-mat-paginator-intl.service.ts
  Eventy/src/app/layout/home/home.component.ts
  Eventy/src/app/layout/nav-bar/nav-bar.component.css
  Eventy/src/app/layout/nav-bar/nav-bar.component.html
  Eventy/src/app/layout/nav-bar/nav-bar.component.ts
  Eventy/src/app/layout/nav-drawer/nav-drawer.component.css
  Eventy/src/app/reviews/create-review/create-review.component.css
  Eventy/src/app/reviews/create-review/create-review.component.html
  Eventy/src/app/reviews/create-review/create-review.component.spec.ts
  Eventy/src/app/reviews/create-review/create-review.component.ts
  Eventy/src/app/reviews/model/review.model.ts
  Eventy/src/app/reviews/reviews.module.ts
  Eventy/src/app/reviews/service/review.service.spec.ts
  Eventy/src/app/reviews/service/review.service.ts
  Eventy/src/app/services/reservation-select-datetime/reservation-select-datetime.component.ts
  Eventy/src/app/user-management/model/users.model.ts
  Eventy/src/app/user-management/user.service.ts
  Eventy/src/styles.css
Labels: enhancement

#44 Improvement/add service
  Eventy/src/app/services/add-service/add-service.component.html
  Eventy/src/app/services/add-service/add-service.component.ts
  Eventy/src/app/services/model/services.model.ts
  Eventy/src/app/services/services/services/services.service.ts
  Eventy/src/app/solutions/model/services.model.ts
Labels: enhancement

#45 [CHANGE] URL for solution details
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/products/product-card/product-card.component.html
  Eventy/src/app/services/service-card/service-card.component.html
Labels: improvement

#46 Improvement/edit service
  Eventy/src/app/services/add-service/add-service.component.ts
  Eventy/src/app/services/edit-service/edit-service.component.html
  Eventy/src/app/services/edit-service/edit-service.component.ts
  Eventy/src/app/services/model/services.model.ts
  Eventy/src/app/services/my-services-view-card/my-services-view-card.component.html
  Eventy/src/app/services/services/services/services.service.ts
  Eventy/src/app/solutions/model/solutions.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.css
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
Labels: enhancement

#47 Feature/product management
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/layout/nav-drawer/nav-drawer.component.html
  Eventy/src/app/products/add-product/add-product.component.css
  Eventy/src/app/products/add-product/add-product.component.html
  Eventy/src/app/products/add-product/add-product.component.spec.ts
  Eventy/src/app/products/add-product/add-product.component.ts
  Eventy/src/app/products/model/products.model.ts
  Eventy/src/app/products/product.service.spec.ts
  Eventy/src/app/products/product.service.ts
  Eventy/src/app/products/products.module.ts
  Eventy/src/app/products/update-product/update-product.component.css
  Eventy/src/app/products/update-product/update-product.component.html
  Eventy/src/app/products/update-product/update-product.component.spec.ts
  Eventy/src/app/products/update-product/update-product.component.ts
  Eventy/src/app/solutions/model/solutions.model.ts
  Eventy/src/app/solutions/services/solutions/solutions-service.service.ts
Labels: enhancement

#48 Feature/product purchase
  Eventy/src/app/events/events.module.ts
  Eventy/src/app/events/own-events-dialog/own-events-dialog.component.css
  Eventy/src/app/events/own-events-dialog/own-events-dialog.component.html
  Eventy/src/app/events/own-events-dialog/own-events-dialog.component.spec.ts
  Eventy/src/app/events/own-events-dialog/own-events-dialog.component.ts
  Eventy/src/app/products/model/purchase.model.ts
  Eventy/src/app/products/product.service.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.html
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
Labels: enhancement

#49 Reviews (admin) - FRONTEND & BACKEND
  Eventy/src/app/app-routing.module.ts
  Eventy/src/app/events/all-events/all-events.component.html
  Eventy/src/app/layout/nav-drawer/nav-drawer.component.html
  Eventy/src/app/reviews/model/review.model.ts
  Eventy/src/app/reviews/pending-reviews/pending-reviews.component.css
  Eventy/src/app/reviews/pending-reviews/pending-reviews.component.html
  Eventy/src/app/reviews/pending-reviews/pending-reviews.component.spec.ts
  Eventy/src/app/reviews/pending-reviews/pending-reviews.component.ts
  Eventy/src/app/reviews/review-details-dialog/review-details-dialog.component.css
  Eventy/src/app/reviews/review-details-dialog/review-details-dialog.component.html
  Eventy/src/app/reviews/review-details-dialog/review-details-dialog.component.spec.ts
  Eventy/src/app/reviews/review-details-dialog/review-details-dialog.component.ts
  Eventy/src/app/reviews/reviews.module.ts
  Eventy/src/app/reviews/service/review.service.ts
  Eventy/src/app/solutions/all-solutions/all-solutions.component.html
Labels: enhancement

#51 Blocks - FRONTEND & BACKEND
  Eventy/src/app/events/event-card/event-card.component.html
  Eventy/src/app/events/event-details/event-details.component.html
  Eventy/src/app/events/event-details/event-details.component.ts
  Eventy/src/app/solutions/solution-details/solution-details.component.ts
  Eventy/src/app/user-management/block-user-dialog/block-user-dialog.component.css
  Eventy/src/app/user-management/block-user-dialog/block-user-dialog.component.html
  Eventy/src/app/user-management/block-user-dialog/block-user-dialog.component.spec.ts
  Eventy/src/app/user-management/block-user-dialog/block-user-dialog.component.ts
  Eventy/src/app/user-management/model/users.model.ts
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.html
  Eventy/src/app/user-management/other-user-profile-page/other-user-profile-page.component.ts
  Eventy/src/app/user-management/user-management.module.ts
  Eventy/src/app/user-management/user.service.ts
Labels: enhancement
